version: '3'
services:
  advisor:
    image: gcr.io/google-containers/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8080:8080
  appnginx:
    build:
      context: ./app
    ports:
      - 3600:3600
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 81:81
    links:
      - appnginx
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
  appapache:
    build:
      context: ./app
    ports:
      - 3601:3600
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
  apache:
    image: httpd
    volumes:
      - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 80:80
    links:
      - appnginx
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 50M
